config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :posts do 
		resources:comments
	end

  
  root 'posts#index'end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class NilClass
  def split(*)
    []
  end
end

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

   def set_locale
    I18n.locale = browser_locales.first || I18n.default_locale
  end

  private def browser_locales
    request.env['HTTP_ACCEPT_LANGUAGE'].split(/;|,/).reject do |x|
      x.start_with?('q')
    end & I18n.available_locales.map(&:to_s)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit 
		if set_comment
			@post = Post.find(params[:post_id])
			@comment = @post.comments.find(params[:id])
		end
	end

	def update
		if set_comment
			@post = Post.find(params[:post_id])
			@comment = @post.comments.find(params[:id])

			if @comment.update(params[:comment].permit(:comment))
				redirect_to post_path(@post)
			else
				render 'edit'
			end
		else
			redirect_to post_path(@post)
		end
	end

	def destroy
		if set_comment
			@post = Post.find(params[:post_id])
			@comment = @post.comments.find(params[:id])
			@comment.destroy
			redirect_to post_path(@post)
		end
	end

	private

	def set_comment
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		current_user.id == @comment.user.id 
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
	end

	def edit
		redirect_to root_path unless set_post
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
				render 'edit'
		end
	end

	def destroy
		if set_post
			@post.destroy
			redirect_to root_path
		end
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end

	def set_post
		 current_user.id == @post.user.id
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author= comment.user.email
	.buttons
		- if current_user.id == comment.user.id
			= link_to t('edit'), edit_post_comment_path(comment.post, comment)
			= link_to t('delete'), [comment.post, comment], method: :delete, data: { confirm: t('are_you_sure') }
		

app/views/comments/_form.html.haml
=simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment, label: t('input_comment')
	= f.submit t('submit')

app/views/comments/edit.html.haml
%h1 
=t('edit_reply')

= simple_form_for([@post, @comment]) do |f|
	= f.input :comment, label: t('input_comment')
	= f.submit t('submit')

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Rails-powered Forum
  = csrf_meta_tags 
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
%body
  %header.main_header.clearfix
    .wrapper 
      #logo
        %p 
        =t('rails_powered_forum')
      #buttons
        -if user_signed_in?
          =link_to t('new_post'), new_post_path
          =link_to t('home'), root_path
          =link_to t('edit_profile'), edit_user_registration_path
          %a{"data-method" => "delete", :href => "/users/sign_out", :rel => "nofollow"} 
            =t('sign_out')
        -else
          = link_to t('sign_up'), new_user_registration_path
          = link_to t('sign_in'), new_user_session_path
  .wrapper
    %p.notice= notice
    %p.alert= alert
  .wrapper
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title, label: t('title_post')
	= f.input :content, label: t('content_post')
	= f.submit t('submit')

app/views/posts/edit.html.haml
%h1 
= t('edit_post')

= render 'form'

=link_to t('cansel'), post_path

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post
			%h2.title= link_to post.title, post
			%p.date
				= t('published_at')
				= time_ago_in_words(post.created_at)
				= t('by')
				= post.user.email

app/views/posts/new.html.haml
%h1 
=t('new_post')

= render 'form'

app/views/posts/show.html.haml
#post_content
	%h1= @post.title
	%p= @post.content

	#comments
		%h2
			= @post.comments.count
			= t('comments')
		= render @post.comments

		%h3 
		= render "comments/form"

	%br/
	%hr/
	%br/
	-if current_user.id == @post.user.id
		= link_to t('edit'), edit_post_path(@post), class: "button"
		= link_to t('delete'), post_path(@post), method: :delete, data: { confirm: t('are_you_sure') }, class: "button"
	